### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by twix20** [Sjantos/OperatingSystems#1]
https://github.com/Sjantos/OperatingSystems/blob/0939ecd6ca0630ba348202e9d157dd4d88777eb3/project1/MyWindow.cpp#L77

Erase na wektorze nie zwalnia obiektu z pamieci.

**Comment by Sjantos** [comment]
[http://www.cplusplus.com/reference/vector/vector/erase/](url) 

> This effectively reduces the container size by the number of elements removed, which are destroyed.

Tak czy siak na końcu funkcji wątku zapomniałem o dealokacji, więc wyciek był, ale myślę że już naprawiłem

**Comment by twix20** [comment]
Destoryed jest sam pointer, a nie obiekt na który wskazuje pointer. Dlatego zanim go wywalisz z vectora, musisz wykonać na tym pointerze delete
